# Rebuild the unmodified LGPL library as replaceable shared libraries.
foreach(module FoundationClasses ModelingData ModelingAlgorithms Visualization ApplicationFramework DataExchange Draw DETools)
  set(BUILD_MODULE_${module} OFF CACHE BOOL "" FORCE)
endforeach()
set(BUILD_TOOLKITS "TKDESTEP;TKDEIGES;TKMesh" CACHE STRING "" FORCE)
set(BUILD_LIBRARY_TYPE Shared CACHE STRING "" FORCE)
set(BUILD_RELEASE_DISABLE_EXCEPTIONS OFF CACHE BOOL "" FORCE)
foreach(option USE_TBB USE_FREETYPE USE_FREEIMAGE USE_FFMPEG USE_VTK USE_TCL USE_TK USE_OPENGL USE_GLES2 USE_RAPIDJSON BUILD_DOC_Overview BUILD_SAMPLES_QT BUILD_INSPECTOR)
  set(${option} OFF CACHE BOOL "" FORCE)
endforeach()
